name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Profile Summary Cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: CigarPandaMan
          BRANCH_NAME: stats
          UTC_OFFSET: -5
          AUTO_PUSH: "false"

      - name: Push to stats branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: stats
          build_dir: profile-summary-card-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
